In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [6]:
# write your code here ^_^
x = np.ones(5)

## Q#2: Create y array with elements equal to 0.

In [8]:
# write your code here ^_^
y= np.zeros(5)

## Q#3: Add x and y arrays.

In [10]:
# write your code here ^_^
x+y

array([1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [20]:
# write your code here ^_^
x.ndim
x.shape
x.size
x.dtype

dtype('float64')

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [31]:
# write your code here ^_^
w = np.array([[11,13,15],[12,14,16]])

numpy.ndarray

## Q#6: Create z array contains the numbers from 1 to 3.

In [33]:
# write your code here ^_^
z=np.array([1,2,3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [62]:
# write your code here ^_^

# Truncate z to match the number of rows in w
z_truncated = z[:2, np.newaxis]

newArray = np.hstack((z_truncated, w))
newArray

array([[ 1, 11, 13, 15],
       [ 2, 12, 14, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [60]:
# write your code here ^_^
for k in newArray:
    for j in k:
        print(j)

1
11
13
15
2
12
14
16


## Q#9: Reverse the columns and rows of "newArray".

In [70]:
# write your code here ^_^
reversed_newArray = np.flip(newArray)
reversed_newArray

array([[16, 14, 12,  2],
       [15, 13, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [68]:
# write your code here ^_^
decremented_newArray = newArray - 1
decremented_newArray

array([[ 0, 10, 12, 14],
       [ 1, 11, 13, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [78]:
# write your code here ^_^
max = newArray.max()
min =newArray.min()

## Q#12: Print the first row of "newArray" using indexing.

In [96]:
# write your code here ^_^
#newArray
print(newArray[0])

[ 1 11 13 15]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [104]:
# write your code here ^_^
print(newArray[1,1])
newArray

12


array([[ 1, 11, 13, 15],
       [ 2, 12, 14, 16]])

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [112]:
# write your code here ^_^
# there is no number in array = 0 
newArray[0, 2] 

13

## Q#15: Change the shape of "newArray" to (9,1).

In [122]:
# Adding one more element to make 9 elements
np.append(newArray, 0).reshape(9, 1)


array([[ 1],
       [11],
       [13],
       [15],
       [ 2],
       [12],
       [14],
       [16],
       [ 0]])

## Q#16: Change the shape of "newArray" to (3,2).

In [126]:
# write your code here ^_^

truncated_newArray = newArray.flatten()[:6].reshape(3, 2)

print(truncated_newArray)


[[ 1 11]
 [13 15]
 [ 2 12]]


# Well Done 🎉